#!/bin/bash

###############################
#                             #
# Developed by: Rowdy Adams   #
# Updated on:   04 Oct 2016   #
#                             # 
###############################

### Alias all commands to themselves for security by using which or whereis
PATH="/home/$USER/perl5/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/$USER/bin"
alias echo='echo';alias sed='sed';alias grep='grep';alias xargs='xargs';alias for='for';alias do='do';alias done='done';
for cmd in `echo $PATH|sed "s/:/ /g"|xargs ls 2>/dev/null|grep -v '/'`;do alias $cmd="$cmd";done;
alias ls='/bin/ls --color=tty -F -A -b -T 0'
###

alias wp='/usr/php/54/usr/bin/php-cli /usr/local/bin/wp'
shopt -s expand_aliases

# Required for gcmd commands #
DIRS=$(find ~/public_html* -maxdepth 5 -type f -name 'wp-config.php')

# Colors
ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
COL_RED=$ESC_SEQ"31;01m"
COL_GREEN=$ESC_SEQ"32;01m"
COL_MGREEN=$ESC_SEQ"32;00m"
COL_PURPLE=$ESC_SEQ"38;5;92;01m"
COL_BLUE=$ESC_SEQ"34;01m"
COL_MAGENTA=$ESC_SEQ"35;01m"
COL_CYAN=$ESC_SEQ"36;01m"
COL_ORANGE=$ESC_SEQ"38;5;208;01m"
COL_CHERRY=$ESC_SEQ"38;5;124;01m"
COL_FORREST=$ESC_SEQ"38;5;22;01m"
# echo -e "\x1b[38;5;92;01m TEXT  \x1b[39;49;00m"

function now() {
date -u +"%Y%m%d-%H%M%S"
}

# WP-CLI is a set of command-line tools for managing WordPress. Quick WP-CLI runs commands in an easy to use wrapper.
#################### START ####################
function qwpcli(){
clear
echo -e "$COL_GREEN 
$COL_GREEN   ____       _     __   $COL_GREEN  _      _____      _______   ____
$COL_GREEN  / __ \__ __(_)___/ /__ $COL_GREEN | | /| / / _ \____/ ___/ /  /  _/$COL_ORANGE  Fixing WordPress $COL_GREEN
$COL_GREEN / /_/ / // / / __/  '_/ $COL_GREEN | |/ |/ / ___/___/ /__/ /___/ /  $COL_ORANGE      Faster! $COL_GREEN
$COL_GREEN \___\_\_,_/_/\__/_/\_\  $COL_GREEN |__/|__/_/       \___/____/___/  $COL_ORANGE  Dev: Rowdy Adams $COL_RESET
$COL_CHERRY
What would you like added to QWPCLI? Let me know!$COL_PURPLE http://goo.gl/forms/R2h7aTZXrX$COL_MGREEN\nType$COL_CYAN qwpcli$COL_MGREEN to return to this menu:

What would you like to work on?                           $COL_GREEN Updated: 04 Oct 2016

  $COL_CYAN wpstats $COL_MGREEN  - Show Version, URL, DB Info, Number of Available Updates
  $COL_CYAN wpcore $COL_MGREEN   - Check Versions, Verify Checksums, Replace Core Files
  $COL_CYAN wpdb $COL_MGREEN     - Optimize and Repair, URL Rewrite
  $COL_CYAN wpplugin $COL_MGREEN - List, (De)activate, Update, Install
  $COL_CYAN wptheme $COL_MGREEN  - List, Change, Update, Install
  $COL_CYAN wpurl $COL_MGREEN    - List and Change URLs
  $COL_CYAN wpuser $COL_MGREEN   - Create User, Set Passwords, Change Roles
  $COL_CYAN wpupdate $COL_MGREEN - Check For or Run Updates, Configure Auto Updates
  $COL_CYAN wpcleanup $COL_MGREEN- Remove All QWPCLI Generated Files
  $COL_CYAN wpworks $COL_MGREEN  - Install Updates, Optimize DB, Run Fixes
  $COL_CYAN wpglobal $COL_MGREEN - Run Commands Across All WordPress Installs (Advanced)
  $COL_CYAN wpmore $COL_MGREEN   - More Commands (Global Actions,$COL_CYAN WSOD Fix$COL_MGREEN, WP Tools, DB List)
$COL_RESET"

### WPCLI FUNCTIONALITY CHECK ###
CHECK=$(wp --skip-plugins --skip-themes core version | wc -l)

if [ $CHECK != '1' ]; then
echo -e "$COL_MAGENTA 
WARNING WPCLI CHECK: [FAILED]
$COL_RESET
WPCLI is having trouble working. Are you in a WordPress directory? If so check for a Coming Soon or Maintenance Mode Plugin. Report this error by runing$COL_CYAN qerror$COL_RESET. 
"
fi
### END WPCLI FUNCTIONALITY CHECK ###

### CHECK FOR COMING SOON PAGES ###
if [[ -d "$(pwd)/wp-content/plugins/coming-soon/" ]] || [[ -d "$(pwd)/wp-content/plugins/coming-soon-page/" ]] || [[ -d "$(pwd)/wp-content/plugins/coming-soon-builder/" ]] || [[ -d "$(pwd)/wp-content/plugins/ultimate-landing-page-and-coming-soon-page/" ]] || [[ -d "$(pwd)/wp-content/plugins/rocket-maintenance-mode/" ]] || [[ -d "$(pwd)/wp-content/plugins/simple-maintenance-mode/" ]] || [[ -d "$(pwd)/wp-content/plugins/coming-soon-maintenance-mode-from-acurax/" ]] || [[ -d "$(pwd)/wp-content/plugins/indeed-coming-soon/" ]]; then
echo -e "$COL_MAGENTA
WARNING:
This site may be using a maintenance mode plugin. Some functions may not work \nproperly.  If you have problems disable the plugin and try again. $COL_RESET
"
fi
### END COMING SOON CHECK ###
}

function wpmore(){
clear
echo -e "$COL_MGREEN
WordPress Specific:
  $COL_CYAN wpwsod $COL_MGREEN   - Guided Walkthrough to Fix WSOD
  $COL_CYAN wpfix $COL_MGREEN    - Run Fixes
  $COL_CYAN wpbackup $COL_MGREEN - Backup Files and Database to Folder or tar.gz
  $COL_CYAN dblist $COL_MGREEN   - Lists Database Names and wp-config.php Locations
  $COL_CYAN wpspeed $COL_MGREEN  - Runs WordPress Speed Checks
  $COL_CYAN wpopt $COL_MGREEN    - Basic Site Optimization and Suggestions
  $COL_CYAN wpinstall $COL_MGREEN- Install WordPress From Scratch 
  $COL_CYAN wptools $COL_MGREEN  - Show WordPress Tools Functions 
  $COL_CYAN wpdbcheck $COL_MGREEN- PHP Based DB Tests 
  $COL_CYAN wpcheck $COL_MGREEN  - Perl Based Plugin/Theme Check 

Helpful Functions:
  $COL_CYAN fcount $COL_MGREEN   - Lists Number of Files in Current Directory
  $COL_CYAN dirsize $COL_MGREEN  - Sorts Directory Contents by Size
  
Troubleshooting:
  $COL_CYAN mailtest $COL_MGREEN - Checks PHP Mail Function
  $COL_CYAN slowmysql $COL_MGREEN- Displays Slow MySQL Queries
  
Check out more wpcli commands at $COL_MAGENTA http://wp-cli.org/commands/ $COL_RESET
"
}

unset HISTFILE
echo -e "\n\n   Quick WP-CLI commands added to current SSH session. For menu, type$COL_CYAN qwpcli$COL_RESET."

### MOVE ERROR LOG AS WPCLI DELETES IT OFTEN ###
NOW=$(date +"%Y_%m_%d-%H%M")
if [ -f error_log ]; then mv error_log error_log.$NOW
fi
### END ERROR LOG RENAME ###

### SHOW MENU ON STARTUP ###
qwpcli
#################### END START ####################

#################### MENUS ####################

### Core Menu ###
function wpcore() {
echo -e "$COL_GREEN
$(wp --skip-plugins --skip-themes core version --extra)
$COL_RESET
Core Options:
(1) Check Version
(2) Verify-Checksums
(3) Replace Core Files
(4) Flush Permalinks
(5) Exit

\tSelection: \c" ; 

read coreSelect && echo ''
case $coreSelect in
	1)	wpCoreVersion;; #Shows core version of WordPress
	2)	wpVerifyCheck;; #Verifys checksums agains WordPress.org
	3)	coreFresh;; #Ask for version, wget and install
	4)	wpRewriteFlush;; #Backup .htaccess and flush permalinks
	5)	return;;
	*)	invalidOption;;
esac 
}
### Database Menu ###
function wpdb() {
###Get the info from the wp-config file

dbname=$(wp --skip-plugins --skip-themes eval 'echo DB_NAME;') ; 
dbuser=$(wp --skip-plugins --skip-themes eval 'echo DB_USER;') ; 
dbpass=$(wp --skip-plugins --skip-themes eval 'echo DB_PASSWORD;') ; 
dbhost=$(wp --skip-plugins --skip-themes eval 'echo DB_HOST;') ;
dbprefix=$(wp --skip-plugins --skip-themes eval 'global $wpdb;echo $wpdb->prefix;') ;

echo -e "$COL_GREEN"
###START DB CONNECTION TEST
if [[ ! -f wp-config.php ]]; then echo Could not find wp-config.php! 
fi
mysql -u $dbuser -p"$dbpass" -e ";" >/dev/null 2>&1 && printf "DB Conn: Success" || printf "DB Conn:$COL_MAGENTA Failure $COL_GREEN"
### END DB CONNECTION TEST
echo -e "
DB User: $dbuser
DB Pass: $dbpass
DB Host: $dbhost
DB Name: $dbname
DB Prfx: $dbprefix
$COL_RESET
Database Options:
(1) Optimize and Repair
(2) URL Rewrite
(3) Clear Expired Transients
(4) Clear Orphaned Post Meta
(5) Exit

\tSelection: \c" ; 

read dbSelect && echo ''
case $dbSelect in
	1)	wpdbOpt ;; #Optimize and repair the database
	2)	wpurlUpdate;; #Change URLs site wide
	3)	wptransient;; #Clear transients
	4)	rmorphanmeta;; #Clear Orphaned Meta
	5)	return;;
	*)	invalidOption;;
esac
}
### Plugin Menu ###
function wpplugin() {
PLUGNUM=$(wp --skip-plugins --skip-themes plugin list | wc -l)
ACTIVEPLUG=$(wp --skip-plugins --skip-themes plugin list | grep -w active | wc -l)
TOTALPLUG=$(wp --skip-plugins --skip-themes plugin list | grep -w -E "inactive|active|must-use" | wc -l)

echo -e "$COL_GREEN
Active Plugins: $ACTIVEPLUG
Total Plugins:  $TOTALPLUG
$COL_RESET
Plugin Options:
(1) List
(2) Activate/Deactivate
(3) Deactivate All
(4) Restore Active Plugins
(5) Install
(6) Install Mojo (Construction Page will be Active)
(7) Exit

\tSelection: \c" ; 

read pluginSelect && echo ''
case $pluginSelect in
	1)	wpPluginList;; #List plugins in a table
	2)	wpPluginToggle;; #Toggle plugins on and off
	3)	wpPluginDeactivate;; #Save active plugin names to a file then deactivate all plugins
	4)	wpPluginActivate;; #Activate plugins deactivated with wpPluginDeactivate then remove the file
	5)	wpPluginInstall;; #Install plugins by slug
	6)	wpMojoInstall;; #Installs the MOJO Marketplace plugin
	7)	return;;
	*)	invalidOption;;
esac
}
### Theme Menu ###
function wptheme() {
echo -e "$COL_GREEN
Template: $(wp --skip-plugins --skip-themes option get template)
Stylesheet: $(wp --skip-plugins --skip-themes option get stylesheet)
$COL_RESET
Theme Options:
(1) List
(2) Change
(3) Install and Activate Default Theme
(4) Install Themes
(5) Exit

\tSelection: \c" ; 

read themeSelect && echo ''
case $themeSelect in
	1)	wpThemeList;; #List available themes
	2)	wpThemeActivate;; #Activate theme from list
	3)	wpThemeDefault;; #Install and activate 2016 theme
	4)	wpThemeInstall;; #Install theme by slug
	5)	return;;
	*)	invalidOption;;
esac
}
### URL Menu ###
function wpurl() {
echo -e "$COL_GREEN
Site URL: $(wp --skip-plugins --skip-themes option get siteurl)
$COL_RESET
URL Options:
(1) Change URLs
(2) List URLs
(3) Exit

\tSelection: \c" ; 

read urlSelect && echo ''
case $urlSelect in
	1)	wpurlUpdate;; #Backup the database and change site URLs
	2)	wpurlList;; #Lists home and site URLs
	3)	return;;
	*)	invalidOption;;
esac
}
### User Menu ###
function wpuser() {
echo -e "
User Options:
(1) List Users
(2) Create Temp User
(3) Remove Temp User
(4) Change Password
(5) Send Password Reset Email
(6) Change User Roles
(7) Change Username
(8) Exit

\tSelection: \c" ;

read userSelect && echo ''
case $userSelect in
	1)	wp --skip-plugins --skip-themes user list --fields=ID,user_login,user_email,roles;; #Only list important information
	2)	wpUserCreate;; #Create temp user HostAdmin
	3)	wpuserr;; #Remove HostAdmin as a user
	4)	wpChangePass;; #Change user password 
	5)	emailPassReset;; #Send password reset email 
	6)	wpUserRole;; #Adjust user roles
	7)	wpChangeUser;; #Change user name
	8)	return;;
	*)	invalidOption;;
esac
}
### Update Menu ###
function wpupdate() {
echo -e " 
Update Options:
(1) Core
(2) Plugins
(3) Themes
(4) All For This Install
(5) Check Available Updates
(6) Disable Auto Updates
(7) Exit

\tSelection: \c" ; 

read updateSelect && echo ''
case $updateSelect in
	1)	wpCoreUpdate;; #Update core files
	2)	wpPluginUpdate;; #Update plugins
	3)	wpThemeUpdate;; #Update themes
	4)	wpUpdateInstall;; #Update entire install
	5)	wpCheckUpdate;; #Show nubmer of missing updates
	6)	wpAutoUpdate;; #Configure Auto updates
	7)	return;;
	*)	invalidOption;;
esac
}

#################### COMMAND FUNCTIONS ####################

##### WPSTATS COMMANDS #####

### SHOW GENERAL WORDPRESS INFORMATION ###
function wpstats(){
###Get the info from the wp-config file

dbname=$(wp --skip-plugins --skip-themes eval 'echo DB_NAME;') ; 
dbuser=$(wp --skip-plugins --skip-themes eval 'echo DB_USER;') ; 
dbpass=$(wp --skip-plugins --skip-themes eval 'echo DB_PASSWORD;') ; 
dbhost=$(wp --skip-plugins --skip-themes eval 'echo DB_HOST;') ;
dbprefix=$(wp --skip-plugins --skip-themes eval 'global $wpdb;echo $wpdb->prefix;') ;

PLUGIN=$(wp --skip-plugins --skip-themes plugin list | grep -w available | wc -l)
THEME=$(wp --skip-plugins --skip-themes theme list | grep -w available | wc -l)
CORE=$(wp --skip-plugins --skip-themes core check-update | grep -w wordpress | wc -l)

echo -e ""

### WPCLI CHECK
CHECK=$(wp --skip-plugins --skip-themes core version | wc -l)

if [ $CHECK == '1' ]; then
	echo -e "$COL_GREEN\rWPCLI Check:$COL_GREEN    [OK] $COL_GREEN"
else
	echo -e "$COL_GREEN\rWPCLI Check:$COL_MAGENTA [FAILED]   Report Errors with$COL_CYAN qerror$COL_GREEN"
fi

### CHECKSUM VERIFICATION
HACK=$(wp --skip-plugins --skip-themes core verify-checksums 2>&1 | wc -l)
if [ $HACK == '1' ]; then
        echo -e "$COL_GREEN\rChecksums:$COL_GREEN      [OK] $COL_GREEN"
else
        echo -e "$COL_GREEN\rChecksums:$COL_MAGENTA      [FAILED]   $HACK Files Do Not Verify $COL_GREEN"
fi

### EVAL PLUGINS/THEMES LOOKING FOR ERRORS
wp --skip-plugins eval 'echo "Eval Plugins:   [OK]\n";'
wp --skip-themes eval 'echo "Eval Themes:    [OK]\n";'

echo -e "\n$COL_GREEN\rWP Version:    $COL_CYAN" `cat wp-includes/version.php | grep "wp_version " | sed "s/.*'\(.*\)'.*/\1/"`
echo -e "$COL_GREEN\rSite URL:     $COL_CYAN" `mysql -u $dbuser -p"$dbpass" $dbname -e "select option_value from $dbprefix""options where option_name""= 'siteurl'"`|sed "s/option_value//" 
echo -e "$COL_GREEN\rHome URL:     $COL_CYAN" `mysql -u $dbuser -p"$dbpass" $dbname -e "select option_value from $dbprefix""options where option_name""= 'home'"`|sed "s/option_value//" 
echo -e "$COL_GREEN\rStylesheet:   $COL_CYAN" `mysql -u $dbuser -p"$dbpass" $dbname -e "select option_value from $dbprefix""options where option_name""= 'stylesheet'"`|sed "s/option_value//" 
echo -e "$COL_GREEN\rTemplate:     $COL_CYAN" `mysql -u $dbuser -p"$dbpass" $dbname -e "select option_value from $dbprefix""options where option_name""= 'template'"`|sed "s/option_value//" 
echo -e "$COL_GREEN"

###START DB CONNECTION TEST
if [[ ! -f wp-config.php ]]; then echo Could not find wp-config.php! 
fi
mysql -u $dbuser -p"$dbpass" -e ";" >/dev/null 2>&1 && printf "Database Conn: $COL_CYAN Success $COL_GREEN \n" || printf "Database Conn: $COL_MAGENTA Failure $COL_GREEN \n"
### END DB CONNECTION TEST

echo -e "Database User: $COL_CYAN $dbuser $COL_GREEN"
echo -e "Database Pass: $COL_CYAN $dbpass $COL_GREEN"
echo -e "Database Host: $COL_CYAN $dbhost $COL_GREEN"
echo -e "Database Name: $COL_CYAN $dbname $COL_GREEN"
echo -e "Database Prfx: $COL_CYAN $dbprefix $COL_GREEN"
echo -e " "

echo -e "Core Updates:  $COL_CYAN $CORE $COL_RESET \t $(php -i 2>/dev/null | grep memory_limit | sed 's/<[^>]*>/ /g') $COL_GREEN"
echo -e "Plugin Updates:$COL_CYAN $PLUGIN $COL_RESET \t $(php -i 2>/dev/null | grep post_max_size | sed 's/<[^>]*>/ /g') $COL_GREEN"
echo -e "Theme Updates: $COL_CYAN $THEME $COL_RESET \t $(php -i 2>/dev/null | grep upload_max_filesize | sed 's/<[^>]*>/ /g') $COL_GREEN"
echo -e "$COL_RESET"
#"
}

##### END WPSTATS COMMANDS #####
##### WPCORE COMMANDS #####

### VERSION ###
function wpCoreVersion(){
wp --skip-plugins --skip-themes core version
}
### CHECKSUMS ###
function wpVerifyCheck(){
wp --skip-plugins --skip-themes core verify-checksums
}
### WGET CORE ###
function coreFresh() {
###  version=$(sed '7q;d' wp-includes/version.php|egrep -o '[0-9.]+')
echo -e "Enter version by number or type latest: " ; read wpver

echo -e "$COL_GREEN\rReplacing existing core with fresh $wpver files\n$COL_RESET"

if [[ ! -e "wordpress-$wpver.tar.gz" ]]; then
	if ! wget -q "https://wordpress.org/wordpress-$wpver.tar.gz"; then
		echo -e "$COL_RED\rUnable to download wordpress-$wpver.tar.gz $COL_RESET"
		return 9
	else echo "Downloading update from https://downloads.wordpress.org/release/wordpress-$wpver.tar.gz..." 
	fi
else echo "wordpress-$wpver.tar.gz already exists! Please rename!"
return 1
fi

temp=$(date -u +"%Y_%m_%d-%H_%M")

echo "Checking for existing WordPress files..."
local wpfiles=$(find -maxdepth 1 -name "wp-*" -o -name index.php -o -name license.txt -o -name readme.html -o -name xmlrpc.php)

if [[ -z "$wpfiles" ]]; then
	echo -e "No existing WordPress files found..."
	else
	oldWP="QWPCLI_CORE_$temp" 
	echo -e "Old WordPress files found! Moving them to$COL_BLUE $oldWP... $COL_RESET"
	mkdir "$oldWP"
	while read -r f; do mv "$f" "$oldWP"; done <<< "$wpfiles"
fi

tar -xf "wordpress-$wpver.tar.gz" --strip-components=1 && echo "Unpacking the update..."
rm -f "wordpress-$wpver.tar.gz" ### && echo "Removed wordpress-$wpver.tar.gz..."

if [[ -d "$oldWP/wp-content" ]]; then
	mv wp-content wp-content_"$temp"  ### && echo "Moved default wp-content to wp-content_$temp..." &&
	mv "$oldWP/wp-content" .  ### && echo "Moved old wp-content back into place..." &&
	rm -rf wp-content_"$temp"  ### && echo "Removed wp-content_$temp..."
fi

if [[ -f "$oldWP/wp-config.php" ]]; then
	cp "$oldWP/wp-config.php" .
	### echo -e "Copied old wp-config.php back into place..."
	echo -e "$COL_GREEN\rSuccess:$COL_RESET Core replaced with stock $wpver files"
	else
	cp wp-config-sample.php wp-config.php
	echo -e "$COL_CYAN\rWarning:$COL_RESET No previous wp-config.php found! Used wp-config-sample.php..."
fi
echo -e "\nCompressing old WordPress core...$COL_GREEN" && tar -zcf "$oldWP".tar.gz "$oldWP" --remove-files && echo -e "Success:$COL_RESET Old WordPress files located$COL_BLUE $oldWP.tar.gz $COL_RESET"
wp --skip-plugins --skip-themes core update-db --quiet
}
### HTACCESS ###
function wpRewriteFlush(){
NOW=$(date +"%Y%m%d_%H%M")
if [ -f .htaccess ]; then cp .htaccess .QWPCLI_htaccess.$NOW
echo -e "$COL_GREEN
Current .htaccess renamed to .QWPCLI_htaccess.$NOW $COL_RESET"
fi

if [ ! -f wp-cli.yml ]; then echo -e "apache_modules:\n\t - mod_rewrite" > wp-cli.yml
fi
wp --skip-plugins --skip-themes rewrite structure $(wp --skip-plugins --skip-themes option get permalink_structure)
wp --skip-plugins --skip-themes rewrite flush --hard
echo -e "$COL_GREEN\rSuccess:$COL_RESET Rewrite Flushed."
}

##### END WPCORE COMMANDS #####
##### WPDB COMMANDS #####

### WPDB ###
function wpdbOpt(){
wp --skip-plugins --skip-themes db repair && wp --skip-plugins --skip-themes db optimize
}

function wptransient(){
wp --skip-plugins --skip-themes transient delete-expired
}

##### END WPDB COMMANDS #####
##### WPPLUGIN COMMANDS #####

### PLUGIN LIST ###
function wpPluginList(){
wp --skip-plugins --skip-themes plugin list
}
### TOGGLE PLUGINS ###
function wpPluginToggle(){
echo -e "$COL_GREEN"
wpPluginList
echo -e "$COL_RESET
What plugin(s) would you like to toggle? If multiple separate by spaces..." 
read PLUGINS
wp --skip-plugins --skip-themes plugin toggle $PLUGINS
}
### DEACTIVATE PLUGINS ###
function wpPluginDeactivate(){
ACTIVEPLUG=$(wp --skip-plugins --skip-themes plugin deactivate --all >.QWPCLI_ACTIVEPLUGINS.txt 2>&1 && <.QWPCLI_ACTIVEPLUGINS.txt awk '$1=="Success:" {print $3}' | tr -d \')
# ALTERNATE wp --skip-plugins --skip-themes option get active_plugins --format=json >.QWPCLI_ACTIVEPLUGINS.txt
# wp --skip-plugins --skip-themes plugin deactivate --all
# '"
wp --skip-plugins --skip-themes plugin list
}
### ACTIVATE PLUGINS ###
function wpPluginActivate(){
ACTIVEPLUGINS=$(<.QWPCLI_ACTIVEPLUGINS.txt awk '$1=="Success:" {print $3}' | tr -d \')
# '
wp --skip-plugins --skip-themes plugin activate $ACTIVEPLUGINS

echo -e "$COL_GREEN\rAttemped plugin reactivation. If errors exist review .QWPCLI_ACTIVEPLUGINS.txt and activate manually. $COL_RESET"

remove_plug_file () { gcmd rm -rf .QWPCLI_ACTIVEPLUGINS.txt; }
trap remove_plug_file EXIT

# ALTERNATE wp --skip-plugins --skip-themes option set active_plugins --format=json < .QWPCLI_ACTIVEPLUGINS.txt
}
### INSTALL PLUGINS ###
function wpPluginInstall(){
echo -e "$COL_GREEN
Recommended Plugins:
   jetpack
   google-captcha
   shortcodes-ultimate
   velvet-blues-update-urls
   sucuri-scanner
   updraftplus
   tk-google-fonts
  
$COL_RESET
What plugin(s) would you like to install (and activate)? Enter slug separated by spaces..."
read INSATALL
wp --skip-plugins --skip-themes plugin install $INSATALL --activate
}

##### END WPPLUGIN COMMANDS #####
##### WPTHEME COMMANDS #####

### LIST THEMES ###
function wpThemeList(){
wp --skip-plugins --skip-themes theme list
}
### ACTIVATE THEME ###
function wpThemeActivate(){
echo -e "$COL_GREEN"
wpThemeList
echo -e "$COL_RESET
What theme would you like to activate?"
read THEME
wp --skip-plugins --skip-themes theme activate $THEME
}
### INSTALL & ACTIVATE DEFAULT THEME ###
function wpThemeDefault(){
wp --skip-plugins --skip-themes theme install twentysixteen --force --activate
}
### INSTALL THEMES ###
function wpThemeInstall() {
echo -e "$COL_GREEN
Recommended Themes:
   twentysixteen
   hueman
   evolve
   customizr
     
Know a good theme? Suggest it!    
$COL_RESET
What theme(s) would you like to install? Enter slug separated by spaces..."
read INSATALL
wp --skip-plugins --skip-themes theme install $INSATALL
}

##### END WPTHEME COMMANDS #####
##### WPURL COMMANDS #####

### URL REWRITE ###
function wpurlUpdate() {
echo -e "$COL_GREEN
Backing up the Database...$COL_RESET"
dbexport
echo -e "$COL_GREEN
Site: $(wp --skip-plugins --skip-themes option get siteurl)
$COL_MAGENTA
WARNING! Old and New URL Prefix should match! For best results only enter domain.com NOT www or http://  

REMEMBER: This is a SEARCH AND REPLACE tool, taking the first value and replacing it with the second
$COL_RESET
Enter Old URL: "
read OLDURL
echo -e "Enter New URL: "
read NEWURL
wp --skip-plugins --skip-themes search-replace $OLDURL $NEWURL --precise --recurse-objects
}
### SHOW SITE/HOME URLS ###
function wpurlList() {
echo -e "$COL_GREEN
Site URL: $(wp --skip-plugins --skip-themes option get siteurl)
Home URL: $(wp --skip-plugins --skip-themes option get home)
$COL_RESET"
}

##### END WPURL COMMANDS #####
##### WPUSER COMMANDS #####

### CREATE TEMP USER HOSTADMIN ###
function wpUserCreate(){
# pass=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9!@#$%^&*_+,./?' | fold -w 10| head -n 1)
URL=$(wp --skip-plugins --skip-themes option get siteurl)
NEWPASS="$(wp --skip-plugins --skip-themes user create HostAdmin HostAdmin@example.com --role=administrator | tail -1 | awk -F ':' '{ print $2 }')"

echo -e "$COL_GREEN
Delete the user when done by running$COL_CYAN wpuserr$COL_RESET!
$COL_RESET
$URL/wp-admin/

UN:$COL_MAGENTA HostAdmin$COL_RESET
PW:$COL_MAGENTA$NEWPASS $COL_RESET\n"

remove_temp_user () { gcmd wpuserr; }
trap remove_temp_user EXIT
}

### REMOVE TEMP USER HOSTADMIN ###
function wpuserr(){
wp --skip-plugins --skip-themes user delete HostAdmin --yes
}
### CHANGE USER PASSWORDS ###
function wpChangePass() {

dbname=$(wp --skip-plugins --skip-themes eval 'echo DB_NAME;') ; 
dbuser=$(wp --skip-plugins --skip-themes eval 'echo DB_USER;') ; 
dbpass=$(wp --skip-plugins --skip-themes eval 'echo DB_PASSWORD;') ; 
dbhost=$(wp --skip-plugins --skip-themes eval 'echo DB_HOST;') ;
dbprefix=$(wp --skip-plugins --skip-themes eval 'global $wpdb;echo $wpdb->prefix;') ;

echo -e "$COL_GREEN"
wp --skip-plugins --skip-themes user list --role=administrator --fields=ID,user_login,display_name,user_email,roles
echo -e "$COL_RESET
User ID: "; read USERID
echo -e "New Password: "; read NEWPASS
# wp --skip-plugins --skip-themes user update $USERID --user_pass=$NEWPASS
# wp --skip-plugins --skip-themes db query "UPDATE "$dbprefix"users SET user_pass = MD5('$NEWPASS') WHERE ID = $USERID;"
mysql -u $dbuser -p$dbpass -D $dbname -e "UPDATE "$dbprefix"users SET user_pass = MD5('$NEWPASS') WHERE ID = $USERID;"

echo -e "\n$COL_GREEN\rSuccess:$COL_RESET Password reset using MySQL\n" 
}

function emailPassReset(){
### Upload file to customer account and run wp --require=emailReset.php emailReset reset_pass --login=username
rm -rf QWPCLI_emailReset.php
echo "
<?php

if( !defined( 'WP_CLI' ) )
        return;

class QWPCLI_Command extends WP_CLI_Command {

        /**
         * Sends a reset email to the specified user.
         */
        function reset_pass( \$args, \$assoc_args ) {
                include_once( 'wp-includes/class-phpass.php' );
                global \$wpdb, \$wp_hasher;
                \$key = wp_generate_password( 20, false );

                \$user_login = \$assoc_args['login'];
                if( is_email( \$user_login ) && email_exists( \$user_login ) ) {
                        \$user = get_user_by( 'email', \$user_login );
                } else if( username_exists( \$user_login ) ) {
                        \$user = get_user_by( 'login', \$user_login );
                } else {
                        WP_CLI::error(\"The supplied username or email address did not match a valid user.\");
                }

                \$wp_hasher = new PasswordHash( 8, true );
                \$hashed = \$wp_hasher->HashPassword( \$key );
                \$keycheck = \$wpdb->update( \$wpdb->users, array( 'user_activation_key' => \$hashed ), array( 'user_login' => \$user->user_login ) );
                if( \$keycheck == false ) {
                        WP_CLI::error(\"There was an error saving your password reset key. Please try again.\");
                }

                \$message = network_site_url(\"wp-login.php?action=rp&key=\$key&login=\" . rawurlencode(\$user_login), 'login');
                \$domain = get_option('siteurl');
                \$domain = preg_replace( '/^https?:\/\//', '', \$domain );
                \$domain = preg_replace( '/^www\./', '', \$domain );
                \$headers[] = 'From: WordPress <wordpress@' . gethostname() . '>';
                \$sent = wp_mail( \$user->user_email, 'Password Reset Link', 'Here is a link to reset the password for ' . \$user->user_login . ': ' . \$message, array( 'From: ' . exec('whoami') . '@' . gethostname() ) );
                if( !\$sent ) {
                    WP_CLI::error('There was an error sending the password reset email.');
                }
                WP_CLI::success( \$message );
        }

}
WP_CLI::add_command( 'QWPCLI_emailReset', 'QWPCLI_Command' );" > QWPCLI_emailReset.php

wp --skip-plugins --skip-themes user list --fields=user_login,user_email,roles

echo -e "\nEnter the$COL_GREEN user_login$COL_RESET above to send the reset email to the$COL_GREEN user_email$COL_RESET address:"

read userReset

wp --skip-plugins --skip-themes --require=QWPCLI_emailReset.php QWPCLI_emailReset reset_pass --login=$userReset

rm -rf QWPCLI_emailReset.php
}

### SET USER ROLES ###
function wpUserRole() {
wp --skip-plugins --skip-themes user list --fields=ID,user_login,user_email,roles
echo -e "
Enter ID of User to adjust Role: "; read ID
echo -e "
(1)$COL_CYAN Administrator$COL_RESET – access to all the admin features within a single site
(2)$COL_CYAN Editor$COL_RESET – publish and manage posts including the posts of other users
(3)$COL_CYAN Author$COL_RESET – publish and manage their own posts
(4)$COL_CYAN Contributor$COL_RESET – write and manage their own posts but cannot publish them
(5)$COL_CYAN Subscriber$COL_RESET – only manage their profile 
(6)$COL_CYAN Exit$COL_RESET

Which Role would you like to assign to user $ID: \c" ; 
read CHANGE && echo ''
case $CHANGE in
	1)	ROLE='administrator'; wp --skip-plugins --skip-themes user set-role $ID $ROLE ;;
	2)	ROLE='editor' ; wp --skip-plugins --skip-themes user set-role $ID $ROLE ;;
	3)	ROLE='author' ; wp --skip-plugins --skip-themes user set-role $ID $ROLE ;;
	4)	ROLE='contributor' ; wp --skip-plugins --skip-themes user set-role $ID $ROLE ;;
	5)	ROLE='subscriber' ; wp --skip-plugins --skip-themes user set-role $ID $ROLE ;;
	6)	return;;
	*)	invalidOption;;
esac
}

function wpChangeUser(){
# need to request entry of new user and old user

wp --skip-plugins --skip-themes user list --fields=ID,user_login,display_name

echo -e "\nWhat user_login (and display_name) would you like to change?" ; read oldUser

echo -e "\nWhat is the new user_login you would like?" ; read newUser

echo -e ""

wp --skip-plugins --skip-themes user update $oldUser --display_name=$newUser

read changeUser <<<$(awk -F\' '/table_prefix/ {print $2}' wp-config.php); read db usr ps pre <<<$(awk -F\' '/DB_/ {print $4}' wp-config.php) && mysql -u $usr -p$ps -D $db -e "UPDATE "$changeUser"users SET user_login = '$newUser' WHERE user_login = '$oldUser'";
#'
echo -e "$COL_GREEN\rSuccess:$COL_RESET Updated user_login and display_name.\n"

wp --skip-plugins --skip-themes user list --fields=ID,user_login,display_name
}

##### END WPUSER COMMANDS #####
##### WPUPDATE COMMANDS #####

### UPDATE CORE FILES TO LATEST VERSION ###
function wpCoreUpdate(){
if [ ! -f .automatic_updates_disabled ]; then
wp --skip-plugins --skip-themes core update
wp --skip-plugins --skip-themes core update-db
else
echo -e "$COL_MAGENTA UPDATE FUNCTIONS DISABLED as long as .automatic_updates_disabled Exists! $COL_RESET"
fi
}
### UPDATE PLUGINS TO LATEST VERSION ###
function wpPluginUpdate(){
if [ ! -f .automatic_updates_disabled ]; then
wp --skip-plugins --skip-themes plugin update --all
else
echo -e "$COL_MAGENTA UPDATE FUNCTIONS DISABLED as long as .automatic_updates_disabled Exists! $COL_RESET"
fi
}
### UPDATE THEMES TO LATEST VERSION ###
function wpThemeUpdate(){
if [ ! -f .automatic_updates_disabled ]; then
wp --skip-plugins --skip-themes theme update --all
else
echo -e "$COL_MAGENTA UPDATE FUNCTIONS DISABLED as long as .automatic_updates_disabled Exists! $COL_RESET"
fi
}
### UPDATE ENTIRE INSTALL TO LATEST VERSION ###
function wpUpdateInstall(){
if [ ! -f .automatic_updates_disabled ]; then
wpCoreUpdate
wpThemeUpdate
wpPluginUpdate
else
echo -e "$COL_MAGENTA UPDATE FUNCTIONS DISABLED as long as .automatic_updates_disabled Exists! $COL_RESET"
fi
}
### DISPLAY AVAILABLE UPDATES ###
function wpCheckUpdate(){
echo -e "$COL_GREEN
----- Core Updates ----- $COL_RESET"
wp --skip-plugins --skip-themes core check-update
echo -e "$COL_GREEN
----- Plugin Updates ----- $COL_RESET"
wp --skip-plugins --skip-themes plugin update --all --dry-run
echo -e "$COL_GREEN
----- Theme Updates ----- $COL_RESET"
wp --skip-plugins --skip-themes theme update --all --dry-run
}

##### END WPUPDATE COMMANDS #####
##### BACKUP #####

function wpbackup(){
NOW=$(date +"%Y_%m_%d_%H-%M")
echo -e "$COL_GREEN
Starting backup.....\n
Exporting Database.....\n"
dbexport
echo -e "Backing Up Files.....$COL_RESET"
	# Makes directory and copy all wordpress files into directory
	mkdir QWPCLI_BACKUP_$NOW && rsync -auvxhr wp* QWPCLI_BACKUP_$NOW;
    	rsync -auvxh .htaccess QWPCLI_BACKUP_$NOW 2>/dev/null || echo -e "\n\tNo .htaccess was present/backed up.";
	rsync -auvxh index.php QWPCLI_BACKUP_$NOW 2>/dev/null || echo -e "\n\tNo index.php was present/backed up.";
	rsync -auvxh license.txt QWPCLI_BACKUP_$NOW 2>/dev/null || echo -e "\n\tNo license.txt was present/backed up.";
	rsync -auvxh readme.html QWPCLI_BACKUP_$NOW 2>/dev/null || echo -e "\n\tNo readme.html was present/backed up.";
	rsync -auvxh xmlrpc.php QWPCLI_BACKUP_$NOW 2>/dev/null || echo -e "\n\tNo xmlrpc.php was present/backed up.";

	mv -f $file QWPCLI_BACKUP_$NOW;
	
	# if user would like, compress directory
	echo -e "\nWould you like to compress (.tar) directory? (y) or (n): \c"; read input;
	if [ $input == 'y' ]; then 
		tar -zvcf QWPCLI_BACKUP_$NOW.tar.gz QWPCLI_BACKUP_$NOW;
		rm -fr QWPCLI_BACKUP_$NOW;
		echo -e "$COL_GREEN\n\tBackup Completed\n\n\tYour Backup is located in:\n\n\tQWPCLI_BACKUP_$NOW.tar.gz\n\n$COL_RESET";
	elif [ $input != 'y' ]; then 
		echo -e "$COL_GREEN\n\tBackup Completed\n\n\tYour Backup is located in:\n\n\tQWPCLI_BACKUP_$NOW\n\n$COL_RESET";
	fi	
}

function wpCoreBackup(){
NOW=$(date +"%Y_%m_%d_%H-%M")
echo -e "$COL_GREEN
Starting backup.....\n
Exporting Database.....\n"
dbexport
echo -e "Backing Up Files.....$COL_RESET"
	# Makes directory and copy all wordpress files into directory
	mkdir QWPCLI_CORE_$NOW && mkdir QWPCLI_CORE_$NOW/wp-content/ && mkdir QWPCLI_CORE_$NOW/wp-content/mu-plugins/ && mkdir QWPCLI_CORE_$NOW/wp-content/plugins/ && mkdir QWPCLI_CORE_$NOW/wp-content/themes/ ;
	rsync -auxr --exclude 'wp-content/' wp* QWPCLI_CORE_$NOW;
	rsync -auxr wp-content/mu-plugins/ QWPCLI_CORE_$NOW/wp-content/mu-plugins/ 2>/dev/null || echo -e "\n\tNo mu-plugins was present/backed up.";
	rsync -auxr wp-content/plugins/ QWPCLI_CORE_$NOW/wp-content/plugins/ 2>/dev/null || echo -e "\n\tNo plugins was present/backed up.";
	rsync -auxr wp-content/themes/ QWPCLI_CORE_$NOW/wp-content/themes/ 2>/dev/null || echo -e "\n\tNo themes was present/backed up.";
    	rsync -auxh {.htaccess,index.php,license.txt,readme.html,xmlrpc.php} QWPCLI_CORE_$NOW 2>/dev/null

	mv -f $file QWPCLI_CORE_$NOW;
	
	# if user would like, compress directory
	# echo -e "\nWould you like to compress (.tar.gz) backup? (y) or (n): \c"; read input;
	# if [ $input == 'y' ]; then 
		tar -zcf QWPCLI_CORE_$NOW.tar.gz QWPCLI_CORE_$NOW;
		rm -fr QWPCLI_CORE_$NOW;
		echo -e "$COL_GREEN\n\tBackup Completed\n\n\tYour Backup is located in:\n\n\tQWPCLI_CORE_$NOW.tar.gz\n\n$COL_RESET";
	# elif [ $input != 'y' ]; then 
	#	echo -e "$COL_GREEN\n\tBackup Completed\n\n\tYour Backup is located in:\n\n\tQWPCLI_CORE_$NOW\n\n$COL_RESET";
	# fi	
}

##### END BACKUP #####
##### WPWORKS #####

function wpworks(){
wpCoreBackup
wpCoreUpdate
wpPluginUpdate
wpThemeUpdate
wpfix
wpdbOpt
echo -e "$COL_GREEN
Success:$COL_RESET Ran Updates. $COL_GREEN
Success:$COL_RESET Transients Cleared. $COL_GREEN
Success:$COL_RESET Flushed Object Cache. $COL_GREEN
Success:$COL_RESET Database Repaired/Optimized. $COL_GREEN
Success:$COL_RESET Rewrite Flushed."
}

##### END WPWORKS #####
### GENERAL FIXES ###

function wpfix(){
echo -e "$COL_BLUE
This could take a moment....$COL_RESET"
wp --skip-plugins --skip-themes transient delete-expired
# wp --skip-plugins --skip-themes media regenerate --yes --quiet
# wpRewriteFlush
rmorphanmeta
wp --skip-plugins --skip-themes cache flush
wp --skip-plugins --skip-themes db repair 
wp --skip-plugins --skip-themes db optimize 
}

### END GENERAL FIXES ###

#################### ADDITIONAL FUNCTIONS ####################
### COUNT FILES IN CURRENT DIR ###
function fcount() { 
find -printf x|wc -c
}
### LIST SIZE OF CURRENT DIR ###
function dirsize() { 
du -ah --max-depth=1 | sort -h
}
### LIST ALL WORDPRESS DATABASES ###
function dblist() { 
find2perl -name "wp-config.php" -exec grep --color -iHn DB_NAME {} \; | perl
}
### EXPORT DATABASE ###
function dbexport(){

dbname=$(wp --skip-plugins --skip-themes eval 'echo DB_NAME;') ; 
dbuser=$(wp --skip-plugins --skip-themes eval 'echo DB_USER;') ; 
dbpass=$(wp --skip-plugins --skip-themes eval 'echo DB_PASSWORD;') ; 
dbhost=$(wp --skip-plugins --skip-themes eval 'echo DB_HOST;') ;
dbprefix=$(wp --skip-plugins --skip-themes eval 'global $wpdb;echo $wpdb->prefix;') ;

echo "Starting export..."
file="$2"
[[ -z "$file" ]] && file="QWPCLI_$dbname"_$(now).sql
mysqldump -h "$dbhost" -u "$dbuser" -p"$dbpass" "$dbname" > "$file" && echo -e "Exported database '$dbname' to file '$file'\n" || echo -e "Failed to export database '$dbname' to file '$file'!\n"
}
### INCORECT MENU OPTION ###
function invalidOption(){
echo -e "$COL_RED\rInvalid Option!$COL_RESET" && return
}
### REPLACE CORE WITH SAME VERSION ###
function wpReplaceCore(){
version=$(sed '7q;d' wp-includes/version.php|egrep -o '[0-9.]+')

echo -e "$COL_GREEN\rReplacing existing core with fresh $version files\n$COL_RESET"

if [[ ! -e "wordpress-$version.tar.gz" ]]; then
	if ! wget -q "https://wordpress.org/wordpress-$version.tar.gz"; then
		echo -e "$COL_RED\rUnable to download wordpress-$version.tar.gz $COL_RESET"
		return 9
	else echo "Downloaded wordpress-$version.tar.gz..." 
	fi
else echo "wordpress-$version.tar.gz already exists! Please rename!"
return 1
fi

temp=$(date -u +"%Y_%m_%d-%H_%M")

echo "Checking for existing WordPress files..."
local wpfiles=$(find -maxdepth 1 -name "wp-*" -o -name index.php -o -name license.txt -o -name readme.html -o -name xmlrpc.php)

if [[ -z "$wpfiles" ]]; then
	echo -e "No existing WordPress files found..."
	else
	oldWP="QWPCLI_CORE_$temp" 
	echo -e "Old WordPress files found! Moving them to$COL_BLUE $oldWP... $COL_RESET"
	mkdir "$oldWP"
	while read -r f; do mv "$f" "$oldWP"; done <<< "$wpfiles"
fi

tar -xf "wordpress-$version.tar.gz" --strip-components=1 && echo "Unpacking the update..."
rm -f "wordpress-$version.tar.gz" ### && echo "Removed wordpress-$version.tar.gz..."

if [[ -d "$oldWP/wp-content" ]]; then
	mv wp-content wp-content_"$temp" ### && echo "Moved default wp-content to wp-content_$temp..." &&
	mv "$oldWP/wp-content" . ###  && echo "Moved old wp-content back into place..." &&
	rm -rf wp-content_"$temp" ### && echo "Removed wp-content_$temp..."
fi

if [[ -f "$oldWP/wp-config.php" ]]; then
	cp "$oldWP/wp-config.php" .
 	### echo -e "Copied old wp-config.php back into place..."
	echo -e "$COL_GREEN\rSuccess:$COL_RESET Core replaced with stock $version files"
	else
	cp wp-config-sample.php wp-config.php
	echo -e "$COL_CYAN\rWarning:$COL_RESET No previous wp-config.php found! Used wp-config-sample.php..."
fi
echo -e "\nCompressing old WordPress core...$COL_GREEN" && tar -zcf "$oldWP".tar.gz "$oldWP" --remove-files && echo -e "Success:$COL_RESET Old WordPress files located$COL_BLUE $oldWP.tar.gz $COL_RESET"
wp --skip-plugins --skip-themes core update-db --quiet
}
### WGET LATEST ###
function coreLatest() {
###  version=$(sed '7q;d' wp-includes/version.php|egrep -o '[0-9.]+')

echo -e "$COL_GREEN\rReplacing existing core with latest version\n$COL_RESET"

if [[ ! -e "wordpress-$wpver.tar.gz" ]]; then
	if ! wget -q "https://wordpress.org/wordpress-latest.tar.gz"; then
		echo -e "$COL_RED\rUnable to download wordpress-latest.tar.gz $COL_RESET"
		return 9
	else echo "Downloaded wordpress-latest.tar.gz..." 
	fi
else echo "wordpress-latest.tar.gz already exists! Please rename!"
return 1
fi

temp=$(date -u +"%Y_%m_%d-%H_%M")

echo "Checking for existing WordPress files..."
local wpfiles=$(find -maxdepth 1 -name "wp-*" -o -name index.php -o -name license.txt -o -name readme.html -o -name xmlrpc.php)

if [[ -z "$wpfiles" ]]; then
	echo -e "No existing WordPress files found..."
	else
	oldWP="QWPCLI_CORE_$temp" 
	echo -e "Old WordPress files found! Moving them to$COL_BLUE $oldWP... $COL_RESET"
	mkdir "$oldWP"
	while read -r f; do mv "$f" "$oldWP"; done <<< "$wpfiles"
fi

tar -xf "wordpress-latest.tar.gz" --strip-components=1 && echo "Unpacking the update..."
rm -f "wordpress-latest.tar.gz" ### && echo "Removed wordpress-latest.tar.gz..."

if [[ -d "$oldWP/wp-content" ]]; then
	mv wp-content wp-content_"$temp"  ### && echo "Moved default wp-content to wp-content_$temp..." &&
	mv "$oldWP/wp-content" .  ### && echo "Moved old wp-content back into place..." &&
	rm -rf wp-content_"$temp" ### && echo "Removed wp-content_$temp..."
fi

if [[ -f "$oldWP/wp-config.php" ]]; then
	cp "$oldWP/wp-config.php" .
	### echo -e "Copied old wp-config.php back into place..."
	echo -e "$COL_GREEN\rSuccess:$COL_RESET Core updated to latest version"
	else
	cp wp-config-sample.php wp-config.php
	echo -e "$COL_CYAN\rWarning:$COL_RESET No previous wp-config.php found! Used wp-config-sample.php..."
fi
echo -e "\nCompressing old WordPress core...$COL_GREEN" && tar -zcf "$oldWP".tar.gz "$oldWP" --remove-files && echo -e "Success:$COL_RESET Old WordPress files located$COL_BLUE $oldWP.tar.gz $COL_RESET"
wp --skip-plugins --skip-themes core update-db --quiet
}
### ERROR REPORTING ###
function qerror(){
DOMAIN=''
DESCRIPTION=''
REPORTED=''
echo -e "$COL_GREEN
Please provide the following information...

What is the domain?$COL_RESET" ; read DOMAIN ;
echo -e "$COL_GREEN
Describe your error and what you were doing: $COL_RESET" ; read DESCRIPTION ;
echo -e "$COL_GREEN
What is your email address?$COL_RESET" ; read REPORTED ;

echo -e "$DOMAIN \n$DESCRIPTION \nReported By: $REPORTED" | mail -s "Quick WPCLI Error Report" radams@bluehost.com && echo -e "\nIssue Report Sent"
}
### Install MOJO ###
function wpMojoInstall(){
wp --skip-plugins --skip-themes plugin uninstall mojo-marketplace mojo-marketplace-wp-plugin mojo-marketplace-wp-plugin-production --deactivate --quiet
# wp --skip-plugins --skip-themes plugin install https://github.com/mojoness/mojo-marketplace-wp-plugin/archive/production.zip --activate
wp --skip-plugins --skip-themes plugin install https://www.mojomarketplace.com/mojo-plugin-assets/updater/release/mojo-marketplace-wp-plugin.zip --activate
wp --skip-plugins --skip-themes option set mm_coming_soon true
# view options by running wp mojo branding --update=
echo -e "$COL_GREEN
Choose a brand for the Mojo Plugin below:
BlueHost
iPower
iPage
FatCow

Brand not listed? type default (or press enter)...$COL_RESET";

read brandSelect && echo ''
case $brandSelect in
	[Bb][Ll][Uu][Ee][Hh][Oo][Ss][Tt])	wp mojo branding --update=BlueHost;;
        [Ff][Aa][Tt][Cc][Oo][Ww])               wp mojo branding --update=FatCow;;
        [Ii][Pp][Oo][Ww][Ee][Rr])		wp mojo branding --update=iPower;;
        [Ii][Pp][Aa][Gg][Ee])                   wp mojo branding --update=iPage;;
        *)					echo -e "$COL_GREEN\rSuccess:$COL_RESET Generic branding set";;
esac
}
### WSOD Fix ###
function wpwsod(){
dbname=$(wp --skip-plugins --skip-themes eval 'echo DB_NAME;') ; 
dbuser=$(wp --skip-plugins --skip-themes eval 'echo DB_USER;') ; 
dbpass=$(wp --skip-plugins --skip-themes eval 'echo DB_PASSWORD;') ; 
dbhost=$(wp --skip-plugins --skip-themes eval 'echo DB_HOST;') ;
dbprefix=$(wp --skip-plugins --skip-themes eval 'global $wpdb;echo $wpdb->prefix;') ;

# THEMENAME=$(echo -e "" `mysql -u $dbuser -p"$dbpass" $dbname -e "select option_value from $dbprefix""options where option_name""= 'stylesheet'"`|sed "s/option_value//")
THEMENAME=$(wp --skip-plugins --skip-themes option get sytelsheet)
### OPTION TO BACKUP ###
echo -e "\nWould you like to make a backup? (Does not include wp-content) (y) or (n): \c"; read input;
if [ $input == 'y' ]; then 
	wpCoreBackup
elif [ $input != 'y' ]; then 
	echo -e "";		
fi

### DEACTIVATE PLUGINS ###
wpPluginDeactivate
echo -e "\nPlugins deactivated. Does the site work? y/n/q \c" ; 
read wsodSelect && echo ''
case $wsodSelect in
	[Yy]*)
		wpPluginActivate
		# TAIL ERROR LOG AND WPCHECK PLUGINS #
		# Downloadwpcheck
		echo -e "$COL_GREEN\nRecent Error Logs: $COL_RESET"
		errl1
		#perl troubleshoot.pl --plugins --wp_cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp"
		echo -e "\nLooks like it was a Plugin issue. \nCheck the error_log to see if you can narrow down the cause."
	;;
	
	[Nn]*) ### DEACTIVATE THEME ###
		wpThemeDefault
		echo -e "\nTheme set to new install of Twentysixteen. Does the site work? y/n/q \c"
		read wsodSelect && echo ''
		case $wsodSelect in
			[Yy]*) 
				wp --skip-plugins --skip-themes theme activate $THEMENAME
				wpPluginActivate
				# WPCHECK ALL AND TAIL ERROR LOG #
				# Downloadwpcheck
				echo -e "$COL_GREEN\nRecent Error Logs: $COL_RESET"
				errl1
				#perl troubleshoot.pl --all --wp_cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp"
				echo -e "\nCould be a Theme or Plugin issue. \nCheck the error_log to see if you can narrow down the cause." 
			;;
				
			### PERMALINKS ###
			[Nn]*) 
				wpRewriteFlush
				echo -e "\nPermalinks/Rewrite Rules flushed. Does the site work? y/n/q \c"
				read wsodSelect && echo ''
				case $wsodSelect in
				[Yy]*) 
					wp --skip-plugins --skip-themes theme activate $THEMENAME
					wpPluginActivate
					# WPCHECK ALL AND TAIL ERROR LOG #
					# Downloadwpcheck
					echo -e "$COL_GREEN\nRecent Error Logs: $COL_RESET"
					errl1
					#perl troubleshoot.pl --all --wp_cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp"
					echo -e "\nPlugins and Theme reactivated. \nCheck the error_log to see if you can narrow down the cause."
				;;
		
				### REPLACE CORE FILES ###
				[Nn]*) 
					wpReplaceCore
					echo -e "\nCore replaced with stock $version files. Does the site work? y/n/q \c"
					read wsodSelect && echo ''
					case $wsodSelect in
					[Yy]*) 
						wp --skip-plugins --skip-themes theme activate $THEMENAME
						wpPluginActivate
						# WPCHECK ALL AND TAIL ERROR LOG #
						# Downloadwpcheck
						echo -e "$COL_GREEN\nRecent Error Logs: $COL_RESET"
						errl1
						#perl troubleshoot.pl --all --wp_cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp"
						echo -e "\nPlugins and Theme reactivated. \nCheck the error_log to see if you can narrow down the cause."
					;;
			
					### ADDITIONAL CHECKS ###
					[Nn]*) 
						# Downloadwpcheck
						echo -e "$COL_GREEN\nRecent Error Logs: $COL_RESET"
						errl1
						#perl troubleshoot.pl --all --wp_cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp"
						echo -e "\nResave the PHP Config and if that fails, seek additional assistance. $COL_RESET"
					echo -e "\nRevert site back to original state? (Reset Plugins and Theme) y/n/q \c"
					read wsodSelect && echo ''
					case $wsodSelect in
					[Yy]*) 
						wp --skip-plugins --skip-themes theme activate $THEMENAME
						wpPluginActivate
						echo -e "$COL_GREEN\nPlugins and Theme restored. $COL_RESET"
					;;	
				
					[Nn]*)
					;;
				
				[qQ]*) ;;
				*) invalidOption;;
				esac 
				;;
			[qQ]*) ;;
			*) invalidOption;;
			esac 
			;;
		[qQ]*) ;;
		*) invalidOption;;
		esac 
		;;
	[qQ]*) ;;
	*) invalidOption;;
	esac 
	;;
[Qq]*) ;;
*) invalidOption;;	
esac


echo -e "$COL_MAGENTA
DONT FORGET:$COL_RESET Clean up after yourself! You may have generated QWPCLI files.

If done run$COL_CYAN wpcleanup$COL_RESET to remove all QWPCLI files.
"
}

### RESTORE FILES WITH RSYNC ###
function restore (){

echo -e "
What backup would you like to restore FILES from?
NOTE: Files are restored from/to your current working directory.

$COL_MAGENTA\rYou are currently in $(dirs) $COL_RESET

(1) Daily
(2) Weekly
(3) Monthly
(4) Exit

\tSelection: \c"  

read var && echo ''
case $var in
        1) echo -e "Please run: $COL_CYAN \nrsync -auvxh ~/../$(whoami).daily$(dirs | cut -c 2-)/ $(dirs)/ $COL_RESET";;
        2) echo -e "Please run: $COL_CYAN \nrsync -auvxh ~/../$(whoami).weekly$(dirs | cut -c 2-)/ $(dirs)/ $COL_RESET";;
        3) echo -e "Please run: $COL_CYAN \nrsync -auvxh ~/../$(whoami).monthly$(dirs | cut -c 2-)/ $(dirs)/ $COL_RESET";;
        4) return;;
        *) invalidOption;;
esac
}

### Disable Auto Updates ###
function wpAutoUpdate(){
echo -e "core\nplugins\nthemes" > .automatic_updates_disabled

echo -e "$COL_GREEN
Success:$COL_RESET Created .automatic_updates_disabled file."
}

function wpeval(){
echo ""
wp eval --skip-plugins 'echo "Eval Plugins: [OK]\n";'
wp eval --skip-themes 'echo "Eval Themes:  [OK]\n";'
wp eval --skip-wordpress 'echo "Eval Core:  [OK]\n";'
echo ""
}

function wpOverhall(){
wpReplaceCore
wp --skip-plugins --skip-themes core update-db
wpRewriteFlush
wp --skip-plugins --skip-themes transient delete-expired
wp --skip-plugins --skip-themes cache flush
wp --skip-plugins --skip-themes media regenerate --yes
wp --skip-plugins --skip-themes db repair 
wp --skip-plugins --skip-themes db optimize

echo -e "$COL_GREEN\r\nSuccess:$COL_RESET Action Completed."
}

function slowmysql(){
echo -e "Total:\n"
egrep -hRo $USER'_[0-9a-z]+' ~/tmp/mysql_slow_queries/ | sort | uniq -c

echo -e "\nDaily\n"
awk '/^use/ {print $2}' ~/tmp/mysql_slow_queries/`date +%Y%m%d`* | sort | uniq -c
}

function wpspeed(){
. <(curl -sS https://raw.githubusercontent.com/rowdya22/wpspeed/master/wpspeed)
}

function mailtest(){
BOXUSER=`whoami`
ADDRESS=`hostname`
LOCATION=`pwd`
PHP_TEMPLATE='
<?php
        $to = $_POST['to'];
        $subject = "Checking Mail Script";
        $body = "Hello, this is Customer Support testing your mail script.";
        $user = get_current_user();
        $address = `hostname`;
        $headers = "From: " . $_POST['from'] . "\r\n" . "X-Mailer: php";
        if (isset($_POST['Submit1'])) { 
                if (mail($to, $subject, $body, $headers)) {
                        echo("<p>Message was sent!</p>");
                } else {
                        echo("<p>Sorry, message delivary failed!</p>");
                }   
        } else {
                echo ("<p>Below is a test that will confirm functionality</br>
                        of the servers ability to use the PHP mail() function.</br></br></br>
                        \"To\" Field can be any email address</br></br>
                        \"From\" Field needs to be a valid email </br>
                         address on the users Hosting Account</br>
            		 or $user@$address</p>");
        }   
?>
<html>
<head>
<title>Email Test</title>
<body>
        <form action="<?php $_PHP_SELF ?>" method="POST">
        To:   <input type="text" name="to" /></br>
        From: <input type="text" name="from" /></br>
        <input type="submit" name= "Submit1" value="Send Mail" />
        </form>
</body>
</html>
'

# assign IP of box to variable address
host -t a $ADDRESS > `pwd`/deleteMe;
awk '{print $4}' deleteMe > deleteMe01;
ADDRESS=`cat deleteMe01`

# assign path of file to variable location
echo $LOCATION > `pwd`/deleteMe;
awk -F public_html '{print $2}' deleteMe > deleteMe01;
LOCATION=`cat deleteMe01`;

# clean up
rm -fr deleteMe{,01};

# create test_email.php file
echo $PHP_TEMPLATE > test_email.php;

URL=$(wp --skip-plugins --skip-themes option get siteurl)

# print out url of test_email.php file
echo -e "\n\tOpen link below by middle clicking on it";
echo -e "\n\t$URL/test_email.php\n";
read -t 120 -p "        --Link will be deleted in 2 minutes or by pushing (Enter)";
rm -fr `pwd`/test_email.php;
echo -e "\n\t--test_email.php removed\n\n\t...Goodbye\n"

}

function wptweak(){
echo -e "$COL_MAGENTA
Now disabling user registration, comments, and pingpacks... $COL_RESET"
sleep 2

#wp --skip-plugins --skip-themes db query "UPDATE $(grep table_prefix wp-config.php | cut -d\' -f2)options SET option_value = '0' WHERE option_name = 'users_can_register';"
#wp --skip-plugins --skip-themes db query "UPDATE $(grep table_prefix wp-config.php | cut -d\' -f2)options SET option_value='closed' WHERE option_name='default_comment_status';"
#wp --skip-plugins --skip-themes db query "UPDATE $(grep table_prefix wp-config.php | cut -d\' -f2)options SET option_value='closed' WHERE option_name='default_ping_status'; "
#wp --skip-plugins --skip-themes db query "UPDATE $(grep table_prefix wp-config.php | cut -d\' -f2)options SET option_value='0' WHERE option_name='default_pingback_flag'; "
#wp --skip-plugins --skip-themes db query "UPDATE $(grep table_prefix wp-config.php | cut -d\' -f2)options SET option_value='1' WHERE option_name='comment_moderation'; "
wp --skip-plugins --skip-themes option set default_comment_status closed
wp --skip-plugins --skip-themes option set default_ping_status closed
wp --skip-plugins --skip-themes option set default_pingback_flag 0
wp --skip-plugins --skip-themes option set users_can_register 0
wp --skip-plugins --skip-themes option set comment_moderation 1
# wp --skip-plugins --skip-themes option set posts_per_page 5

echo -e "$COL_MAGENTA
Now disabling comments and pingbacks on existing content... $COL_RESET"
sleep 1
dbprefix=$(wp --skip-plugins --skip-themes eval 'global $wpdb;echo $wpdb->prefix;') ;
wp --skip-plugins --skip-themes db query "UPDATE ${dbprefix}posts SET comment_status='closed', ping_status='closed';"

echo -e "$COL_GREEN
Success:$COL_RESET WordPress updated with recommended settings."
}

### CLEAN UP QWPCLI FILES ###
function wpcleanup(){
unset HISTFILE && find ~/public_html*/ -maxdepth 5 \( -name "QWPCLI_*" -o -name ".QWPCLI_*" \)|xargs rm -rfv
}

function Downloadwpcheck(){
if [ ! -f troubleshoot.pl ]; then
wget https://github.com/voldemortensen/wcslc-2015/raw/master/troubleshoot.pl
echo -e "$COL_GREEN \nLatest troubleshoot.pl downloaded $COL_RESET"
fi

clean_up_files () { find ~/public_html*/ -maxdepth 5 \( -name "troubleshoot.pl" -o -name "qwpcli.md5" \)|xargs rm -rf; }
trap clean_up_files EXIT
}

function wpcheck(){
Downloadwpcheck
echo -e "
What would you like to check?:
(1) All
(2) Plugins
(3) Themes
(4) Data
(5) Exit

\tSelection: \c" ; 

read coreSelect && echo ''
case $coreSelect in
	1)	perl troubleshoot.pl --all --wp_cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp" ;; 
	2)	perl troubleshoot.pl --plugins --wp_cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp" ;; 
	3)	perl troubleshoot.pl --themes --wp_cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp" ;; 
        4)      perl troubleshoot.pl --data --wp_cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp" ;;
	5)	return;;
	*)	invalidOption;;
esac 
}

# REMOVE ORPHANDED POSTMETA
function rmorphanmeta(){
dbprefix=$(wp --skip-plugins --skip-themes eval 'global $wpdb;echo $wpdb->prefix;') ;
wp --skip-plugins --skip-themes db query "DELETE pm FROM ${dbprefix}postmeta pm LEFT JOIN ${dbprefix}posts wp ON wp.ID = pm.post_id WHERE wp.ID IS NULL";

echo -e "$COL_GREEN\rSuccess:$COL_RESET Orphanded post_meta data removed using MySQL" 
}

function wpdbcheck(){
if [ ! -f wpdbtest.php ]; then
wget http://radams.bluehoststaff.com/script/databasetest
mv databasetest wpdbtest.php
echo -e "$COL_GREEN \nLatest wpdbtest.php downloaded $COL_RESET"
fi

echo -e "$COL_GREEN \nBegin Test by visting http://domain.com/wpdbtest.php \n $COL_RESET"

clean_up_wpdbcheck () { find ~/public_html*/ -maxdepth 5 \( -name "wpdbtest.php" \)|xargs rm -rf; }
trap clean_up_wpdbcheck EXIT
}

### Find error logs modified in the last 10 days and show the last 10 lines
function errl1(){
find -maxdepth 1 -mtime -10 -type f -iname "error_log*" -print0 | xargs -0 tail
}

function wpcolors(){
echo -e "
$COL_RED This is RED $COL_RESET
$COL_GREEN This is GREEN $COL_RESET
$COL_MGREEN This is MGREEN $COL_RESET
$COL_PURPLE This is PURPLE $COL_RESET
$COL_BLUE This is BLUE $COL_RESET
$COL_MAGENTA This is MAGENTA $COL_RESET
$COL_CYAN This is CYAN $COL_RESET
$COL_ORANGE This is ORANGE $COL_RESET
$COL_CHERRY This is CHERRY $COL_RESET
$COL_FORREST This is FORREST $COL_RESET
"
}

#################### GLOABAL FUNCTIONS ####################
function wpglobal(){
clear
wpLocation=($(find ~/public_html* -maxdepth 5 -type f -name 'wp-config.php'))
# wpLocation=$DIRS

originalDir=($(pwd))
echo -e "$COL_GREEN
   _______     __        __  ___      __  _                
  / ___/ /__  / /  ___ _/ / / _ |____/ /_(_)__  ___  ___  $COL_ORANGE  Fixing WordPress $COL_GREEN  
 / (_ / / _ \/ _ \/ _  / / / __ / __/ __/ / _ \/ _ \(_-<  $COL_ORANGE      Faster! $COL_GREEN
 \___/_/\___/_.__/\_,_/_/ /_/ |_\__/\__/_/\___/_//_/___/  $COL_ORANGE  Dev: Rowdy Adams 
$COL_MGREEN
What global actions would you like to take? 

(1) Replace Core With Existing Version
(2) Install Updates, Flush Rewrite Rules, Flush Cache, Opt & Repair DB
(3) Clear Transients, Optimize/Repair Database
(4) Update Core, Plugins, and Themes
(5) Verify Checksums
(6) Check For Available Updates
(7) Disable (Bluehost) Auto Updates
(8) Check Theme/Plugin Conflicts
(9) Overhall (Replace Core, Flush Permalinks, Flush Cache, Media Regenerate, Opt & Repair DB)
(0) Exit
$COL_MAGENTA
Want to run another command? use$COL_CYAN gcmd [COMMAND]$COL_MAGENTA to run any command in all WordPress directories!
$COL_RESET
\tSelection: \c" ;
read globalSelect && echo ''

for ((i = 0; i < ${#wpLocation[@]}; i++))
	do
	case $globalSelect in
	1)	wpgReplaceCore ${wpLocation[$i]}
		(($i+1))
		;;
	2)	wpgWorks ${wpLocation[$i]}
		(($i+1))
		;;
	3)	wpgDB ${wpLocation[$i]}
		(($i+1))
		;;
	4)	wpgUpdate ${wpLocation[$i]}
		(($i+1))
		;;
	5)	wpgVerifyCheck ${wpLocation[$i]}
		(($i+1))
		;;
	6)	wpgCheckUpdate ${wpLocation[$i]}
		(($i+1))
		;;
	7)	wpgAutoUpdate ${wpLocation[$i]}
		(($i+1))
		;;
	8)	wpgEval ${wpLocation[$i]}
		(($i+1))
		;;
	9)	wpgOverhall ${wpLocation[$i]}
		(($i+1))
		;;
	0)	return;;
	*)	invalidOption;;
	esac
		
done

echo -e "$COL_GREEN
Success:$COL_RESET Global operation completed.\n"

cd $originalDir
}


function wpgGlobal(){
NOW=$(date +"%Y_%m_%d")
if [ -f error_log ]; then mv error_log error_log.$NOW
fi
### Determine WordPress location
if [ $1 == "wp-config.php" ]; then
	local loc="Current Working Directory"	
else
	local loc=${1%wp-config.php*}
fi

### Change to the WordPress location
cd ~/public_html${loc##/home*public_html}
echo -e "\n$COL_BLUE----- Updating $(pwd) -----$COL_RESET"
### Start Global Actions ###
}
############################################################

function wpgReplaceCore(){
wpgGlobal "$@"
### Start Global Actions ###
wpReplaceCore
}

function wpgWorks(){
wpgGlobal "$@"
### Start Global Actions ###
coreLatest
wpworks
}

function wpgDB(){
wpgGlobal "$@"
### Start Global Actions ###
wp --skip-plugins --skip-themes transient delete-expired
wpdbOpt
}

function wpgWSOD(){
wpgGlobal "$@"
### Start Global Actions ###
wpwsod
}

function wpgVerifyCheck(){
wpgGlobal "$@"
### Start Global Actions ###
wpVerifyCheck
}

### Disables Auto Updates For Each Site
function wpgAutoUpdate(){
wpgGlobal "$@"
### Start Global Actions ###
wpAutoUpdate
}

### Displays available updates 
function wpgCheckUpdate(){
wpgGlobal "$@"
### Start Global Actions ###
wpCheckUpdate
}

function wpgEval(){
wpgGlobal "$@"
### Start Global Actions ###
wpeval
}

function wpgOverhall(){
wpgGlobal "$@"
### Start Global Actions ###
wpOverhall
}

function wpgUpdate(){
wpgGlobal "$@"
### Start Global Actions ###
wp --skip-plugins --skip-themes core update
wp --skip-plugins --skip-themes core update-db
wp --skip-plugins --skip-themes plugin update --all
wp --skip-plugins --skip-themes theme update --all
}

function gcmd(){
#DIRS=$(find ~/public_html* -maxdepth 5 -type f -name 'wp-config.php')
for DIR in $DIRS; do
    CDIR=$(dirname $DIR)
    cd $CDIR;
    echo -e "\n$COL_BLUE----- Updating $(pwd) -----$COL_RESET"
if [[ "$1" == 'wp' ]];then
    /usr/php/54/usr/bin/php-cli /usr/local/bin/$@;
else
    $@;
fi
    cd - >/dev/null
done
}
#################### END GLOABAL FUNCTIONS ####################

#################### START INSTALL FUNCTIONS ####################
function wpinstall(){
clear
echo -e "$COL_GREEN
  _      _____    ____           __         __ __   
 | | /| / / _ \  /  _/___   ___ / /_ ___ _ / // /         $COL_ORANGE  Fixing WordPress $COL_GREEN
 | |/ |/ / ___/ _/ / / _ \ (_-</ __// _ \`// // /         $COL_ORANGE      Faster! $COL_GREEN 
 |__/|__/_/    /___//_//_//___/\__/ \_,_//_//_/           $COL_ORANGE  Dev: Rowdy Adams $COL_RESET"


# accept user input for the databse info
echo -e "$COL_MAGENTA
This setup will guide you through a manual WordPress install.

Make sure you are in the folder you want to install WordPress and\nthere are no existing WordPress files.\n

---To begin create a database in cPanel and then enter the needed information--- $COL_RESET"
echo -e "$COL_GREEN
Database Name: $COL_RESET"
read -e dbname
echo -e "$COL_GREEN 
Database User: $COL_RESET"
read -e dbuser
echo -e "$COL_GREEN 
Database Password: $COL_RESET"
read -e dbpass
echo -e "$COL_GREEN
Table Prefix (default: wp_): $COL_RESET"
read -e dbprefix

# download the WordPress core files
wp --skip-plugins --skip-themes core download

# create the wp-config file with our standard setup
wp --skip-plugins --skip-themes core config --dbname=$dbname --dbuser=$dbuser --dbpass=$dbpass --dbprefix=$dbprefix

wp --skip-plugins --skip-themes core install --prompt
wp --skip-plugins --skip-themes plugin uninstall hello --deactivate --quiet

echo -e "$COL_MAGENTA
Now installing suggested plugins and themes.... $COL_RESET"
sleep 2
## wp --skip-plugins --skip-themes plugin install jetpack sucuri-scanner google-captcha shortcodes-ultimate
wpPluginInstall
wpThemeInstall
wp --skip-plugins --skip-themes plugin update --all
wp --skip-plugins --skip-themes theme update --all

echo -e "$COL_MAGENTA
Now disabling user registration, comments, and pingpacks... $COL_RESET"
sleep 2
# read db usr ps pre <<<$(awk -F\' '/DB_/ {print $4}' wp-config.php) 
# mysql -u $usr -p$ps -D $db -e "UPDATE wp_options SET option_value = '0' WHERE option_name = 'users_can_register';" 
# mysql -u $usr -p$ps -D $db -e "UPDATE wp_options SET option_value='closed' WHERE option_name='default_comment_status';"
# mysql -u $usr -p$ps -D $db -e "UPDATE wp_options SET option_value='closed' WHERE option_name='default_ping_status'; "
# mysql -u $usr -p$ps -D $db -e "UPDATE wp_posts SET comment_status='closed', ping_status='closed';"

wp --skip-plugins --skip-themes option set users_can_register 0
wp --skip-plugins --skip-themes option set default_comment_status closed
wp --skip-plugins --skip-themes option set default_ping_status closed
wp --skip-plugins --skip-themes option set default_pingback_flag 0
wp --skip-plugins --skip-themes option set comment_moderation 1
wp --skip-plugins --skip-themes option set start_of_week 0
wp --skip-plugins --skip-themes option set posts_per_page 5
wp --skip-plugins --skip-themes option set date_format 'j F Y'
wp --skip-plugins --skip-themes option set time_format 'g:i A'

echo -e "$COL_MAGENTA
Now disabling comments and pingbacks on existing content... $COL_RESET"
sleep 1
wp --skip-plugins --skip-themes post update $(wp --skip-plugins --skip-themes post list --format=ids) --comment_status=closed
wp --skip-plugins --skip-themes post update $(wp --skip-plugins --skip-themes post list --format=ids) --ping_status=closed

echo -e "$COL_GREEN
Success:$COL_RESET WordPress installed with recommended plugins and settings."
sleep 3
wpstats
}
#################### END INSTALL FUNCTIONS ####################

#################### START OPTIMIZATION FUNCTIONS ####################
function wpopt(){
clear

echo -e "$COL_GREEN 
  _      _____    ____       __  _       _          __  _         
 | | /| / / _ \  / __ \___  / /_(_)_ _  (_)__ ___ _/ /_(_)__  ___ 
 | |/ |/ / ___/ / /_/ / _ \/ __/ /  ' \/ /_ // _  / __/ / _ \/ _ \\
 |__/|__/_/     \____/ .__/\__/_/_/_/_/_//__/\_,_/\__/_/\___/_//_/
                    /_/                                           
$COL_MAGENTA
WARNING: THIS IS AN ADVANCED MENU. MAKE SURE THAT YOU KNOW WHAT YOU ARE DOING! \nCheck if there is existing optimization code in the .htaccess before modifying. If code is duplicated it can cause the site to break. \n $COL_RESET

(1) WP Speed Report
(2) Backup .htaccess
(3) Enable Gzip Compression (.htaccess)
(4) Enable Expired Headers (.htaccess)
(5) Revert Changes
(6) Quick Optimize 
(7) Install Recommended Plugins (Manual Setup)
(8) Exit

\tSelection: \c" ;

read optSelect && echo ''
case $optSelect in
	1)	wpSpeedReport;; #Shows wpspeed optimization report
	2)	wpBackupHtaccess;; 
	3)	wpEnableGzip;; 
	4)	wpEnableExpiredHeaders;; 
	5)	wpUndoOpt;;
	6)	wpQuickOpt;;
	7)	wpOptPlugInstall;;
	8)	return;;
	*)	invalidOption;;
esac
}

function wpSpeedReport(){
echo -ne "\n\t\t\tOptimization report built by cmiles\n"
sleep 0.5
. <(curl -sS https://raw.githubusercontent.com/rowdya22/wpspeed/master/wpspeed)
clear
wpspeed
}

function wpBackupHtaccess(){
# if user would like, make backup
echo -e "\nWould you like to do a full site backup? (y) or (n): \c"; read input;
if [ $input == 'y' ]; then 
	wpbackup
elif [ $input != 'y' ]; then 
	if [[ ! -f .htaccess ]]; then echo Could not find .htaccess! 
	fi
	NOW=$(date +"%Y%m%d_%H%M")
	if [ -f .htaccess ]; then cp .htaccess .QWPCLI_htaccess_preopt
		echo -e "$COL_GREEN
	Current .htaccess backed up to .QWPCLI_htaccess_preopt $COL_RESET \n"
	fi
fi
}

function wpEnableGzip(){
if [[ ! -f .htaccess ]]; then echo Could not find .htaccess! 
fi

if [ ! -f .QWPCLI_htaccess_preopt ]; then cp .htaccess .QWPCLI_htaccess_preopt
	echo -e "$COL_GREEN
Current .htaccess backed up to .QWPCLI_htaccess_preopt $COL_RESET \n"
fi

if [ -f .htaccess ]; then
echo -e "\n
########## Enable Gzip Compression Start ##########
<ifmodule mod_deflate.c>

AddOutputFilterByType DEFLATE image/gif image/png image/jpeg image/x-icon application/pdf application/javascript application/x-javascript text/plain text/html text/css text/x-component text/xml application/json </ifmodule>
########## End Enable Gzip Compression ##########" >> .htaccess

echo -e "$COL_GREEN
Success:$COL_RESET Gzip Compression code added to .htaccess\n"
fi
}

function wpEnableExpiredHeaders(){
if [[ ! -f .htaccess ]]; then echo Could not find .htaccess! 
fi

if [ ! -f .QWPCLI_htaccess_preopt ]; then cp .htaccess .QWPCLI_htaccess_preopt
	echo -e "$COL_GREEN
Current .htaccess backed up to .QWPCLI_htaccess_preopt $COL_RESET \n"
fi

if [ -f .htaccess ]; then
echo -e "\n
########## Add Leverage Browser Caching ##########
AddType image/x-icon .ico

<IfModule mod_headers.c>
# YEAR
<FilesMatch \".(ico|gif|jpg|jpeg|png|flv|pdf)$\">
 Header set Cache-Control "max-age=29030400"
</FilesMatch>
# WEEK
<FilesMatch \".(js|css|swf)$\">
 Header set Cache-Control "max-age=604800"
</FilesMatch>
# 24 HOURS
<FilesMatch \".(html|htm|txt|php)$\">
 Header set Cache-Control "max-age=86400"
</FilesMatch>
</IfModule>
########## End Leverage Browser Caching ##########" >> .htaccess

echo -e "$COL_GREEN
Success:$COL_RESET Leverage Browser Caching code added to .htaccess\n"
fi
}

function wpUndoOpt(){
if [[ -f QWPCLI_BACKUP_* ]]; then
	tar -zxvf QWPCLI_BACKUP_* --strip-components=1
fi

if [[ ! -f QWPCLI_BACKUP_* ]]; then

	if [[ ! -f .QWPCLI_htaccess_preopt ]]; then echo Could not find .htaccess backup! 
	fi

	if [[ -f .QWPCLI_htaccess_preopt ]]; then
	mv .htaccess .QWPCLI_htaccess_opt
	mv .QWPCLI_htaccess_preopt .htaccess

	echo -e "$COL_GREEN
	\rSuccess:$COL_RESET .htaccess file reset from backup\n"
	fi
fi
}

function wpQuickOpt(){
wpBackupHtaccess
wpEnableGzip
wpEnableExpiredHeaders
wptransient
wpdbOpt
}

function wpOptPlugInstall(){
wp --skip-plugins --skip-themes plugin install wp-super-cache wp-optimize ewww-image-optimizer --activate

echo -e "\nBe sure to configure the plugins for best results\n"
}

#################### END OPTIMIZATION FUNCTIONS ####################

#################### START WP-TOOLS FUNCTIONS ####################
function wptools(){
clear
echo -e "$COL_GREEN
  _      _____    ______          __  
 | | /| / / _ \  /_  __/__  ___  / /__                    $COL_ORANGE  Fixing WordPress $COL_GREEN  
 | |/ |/ / ___/   / / / _ \/ _ \/ (_-<                    $COL_ORANGE      Faster! $COL_GREEN
 |__/|__/_/      /_/  \___/\___/_/___/                    $COL_ORANGE  Dev: Rowdy Adams $COL_MGREEN

This menu allows you to tap into the power of WordPress Tools. To skip the menu,
type$COL_CYAN wptools$COL_MGREEN and press tab twice to view options.$COL_MAGENTA All actions viewable in the 
WordPress Tools GUI.$COL_MGREEN Choose a Function below:$COL_RESET

(1) Backup  - Backup site through WordPress Tools (May not include all content)
(2) Restore - Restore site & database from existing WordPress Tools backup
(3) Upgrade - Backup and update site, plugins, themes. If errors exist revert.
(4) Exit

\tSelection: \c" ;

read toolsSelect && echo ''
case $toolsSelect in
	1)	wptoolsbackup;; 
	2)	wptoolsrestore;; 
	3)	wptoolsupgrade;; 
	4)	return;;
	*)	invalidOption;;
esac
}

function wptoolsbackup(){
DIR=$(pwd)
HASHDIR="$(echo "$(dirs)" | cut -d "~" -f 2)/"
WPDIR="$(echo "$(dirs)" | sed 's/^..//' )/"
BACKUPDIR=$(perl -e'my $a = unpack "H*", "$ARGV[0]"; print $a;' $HASHDIR)

echo -e "$COL_GREEN
Backup running... $COL_RESET"
cd ~
wp-tools backup --force --path=$WPDIR --backupdir=backupwordpress/$BACKUPDIR --wp-cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp"
cd $DIR
}

function wptoolsrestore(){
DIR=$(pwd)
WPPATH="/$(echo "$(dirs)" | sed 's/^..//' )/"
HASHDIR=$(perl -e'my $a = unpack "H*", $ARGV[0];print $a;' $WPPATH)

cd ~
WPFILES="backupwordpress/$HASHDIR/*.tar.gz"

for i in $WPFILES; do

    TIME=$(perl -e'
    my $file = $ARGV[0];
    my ($time) = $file =~ /wp_backup(\d+)/;
    my $date = "date -d\@$time";
    print `$date`;
    ' $i)

    MANIFEST=$(dd bs=8192 count=1 if=$i 2>/dev/null | tar -xOz wp_backup.MANIFEST 2>/dev/null)
    THINGS=$(echo $MANIFEST | tr " " "\n")

    echo $TIME
    for thing in $THINGS; do
        echo $thing
    done
    echo ""

done

echo -e "Enter epoch time of the restore point (e.g. time:$COL_MAGENTA 1339826400$COL_RESET):" ; read TIMESTAMP

wp-tools restore --force --backupfile=backupwordpress/$HASHDIR/wp_backup$TIMESTAMP.tar.gz --wp-cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp"

cd $DIR
}

function wptoolsupgrade(){
#Required Syntax: wp-tools upgrade --path=public_html/site --backupdir=backupwordpress/$BACKUPDIR --wp-cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp"

DIR=$(pwd)
HASHDIR="$(echo "$(dirs)" | cut -d "~" -f 2)/"
WPDIR="$(echo "$(dirs)" | sed 's/^..//' )/"
BACKUPDIR=$(perl -e'my $a = unpack "H*", "$ARGV[0]"; print $a;' $HASHDIR)

if [ ! -f .automatic_updates_disabled ]; then
echo -e "$COL_GREEN
Upgrade running... $COL_RESET"
cd ~
wp-tools upgrade --force --path=$WPDIR --backupdir=backupwordpress/$BACKUPDIR --wp-cli="/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini /usr/local/bin/wp"
cd $DIR
else
echo -e "$COL_MAGENTA UPDATE FUNCTIONS DISABLED as long as .automatic_updates_disabled Exists! $COL_RESET"
fi
}

#################### END WP-TOOLS FUNCTIONS ####################

###

##########UNDER CONSTRUCTION##########
function wpGlobalTemplate(){
wpLocation=($(find ~/public_html -maxdepth 5 -type f -name 'wp-config.php'))
originalDir=($(pwd))
for ((i = 0; i < ${#wpLocation[@]}; i++))
	do
		functionname ${wpLocation[$i]}
		(($i+1))
	done
echo -e "$COL_GREEN
Success:$COL_RESET Operation completed.\n"

cd $originalDir
}

function check(){
if [ ! -f .automatic_updates_disabled ]; then
echo "Auto Updates not disabled. Continue as Normal"
else
echo -e "$COL_MAGENTA Auto Updates DISABLED. Not Updating $COL_RESET"
fi
}

function enableSSL(){
sslredirect="test"
#sslredirect="
# Custom subdomain .htaccess SSL + WordPress
#RewriteEngine On
#RewriteCond %{HTTP_HOST} ^subdomain.maindomain.com$
#RewriteCond %{REQUEST_URI} !^/subfolder/
#RewriteRule ^(.*)$ /subfolder/$1
#RewriteCond %{HTTP_HOST} ^subdomain.maindomain.com$
#RewriteRule ^(/)?$ subfolder/index.php [L]
# End custom subdomain .htaccess
#"

sed -ei "s/# END WordPress/# END WordPress\n$sslredriect/" .htaccess
}

function wpRevert(){

dbname=$(wp --skip-plugins --skip-themes eval 'echo DB_NAME;') ; 
dbuser=$(wp --skip-plugins --skip-themes eval 'echo DB_USER;') ; 
dbpass=$(wp --skip-plugins --skip-themes eval 'echo DB_PASSWORD;') ; 
dbhost=$(wp --skip-plugins --skip-themes eval 'echo DB_HOST;') ;
dbprefix=$(wp --skip-plugins --skip-themes eval 'global $wpdb;echo $wpdb->prefix;') ;

if [[ ! -f QWPCLI_BACKUP_* && ! -f QWPCLI_CORE_* ]]; then
echo -e "$COL_MAGENTA
Warning:$COL_RESET No backup found!\n"
fi

if [[ -f QWPCLI_BACKUP_* ]]; then
	tar -zxvf QWPCLI_BACKUP_* --strip-components=1
	wp --skip-plugins --skip-themes db import QWPCLI_$dbname_*
	rm -rf QWPCLI_BACKUP_* QWPCLI_$dbname_*
echo -e "$COL_GREEN
Success:$COL_RESET Files and Database restored from backup.\n"
fi

if [[ -f QWPCLI_CORE_* ]]; then
	tar -zxvf QWPCLI_CORE_* --strip-components=1
	rm -rf QWPCLI_CORE_*
echo -e "$COL_GREEN
Success:$COL_RESET Core files restored from backup.\n"
fi
}

# use_notification_emails () { echo -e "Quick WPCLI Used on This Site: $(pwd)\n$(wp --skip-plugins --skip-themes option get siteurl)" | mail -s "Quick WPCLI Usage Notifcation" radams@bluehost.com; }
# trap use_notification_emails EXIT


#####
function improvewp(){
EMAIL=''
echo -e "\nDo you want Bluehost to improve its WordPress troubleshooting tools? (y) or (n): \c"; read input;
if [ $input == 'y' ]; then 
echo -e "$COL_GREEN
What is your email address?$COL_RESET" ; read EMAIL
echo -e "
Please email the following information to radams@bluehost.com 
------------------------------------------------------------------
Site: $(wp --skip-plugins --skip-themes option get siteurl)

What was the main issue?

How did you correct the problem?

What tools/information do you use when troubleshooting WordPress?

Where do you find that information?

What information do you wish was more easily accessible?
	
What are your most common issues with WordPress?	

------------------------------------------------------------------

Please be as detailed as possible in order to help our insternal tools to improve.
" | mail -s "WordPress Feedback Report" $EMAIL && echo -e ''

echo -e "$COL_ORANGE
Please answer the questions which were just emailed to you after troubleshooting to help us improve our internal tools. 
Send all answers to:$COL_GREEN radams@bluehost.com $COL_RESET"

elif [ $input != 'y' ]; then 
echo -e "$COL_GREEN
Please view: https://media.giphy.com/media/1iTpx5PpzRugcrZK/giphy.gif $COL_RESET"
fi
}
# improvewp

function mkdev(){
# read -r dbhost dbname dbpass dbuser dbprodprefix <<< $(cat wp-config.php | egrep "^[^/].*[\"']DB_(NAME|USER|PASSWORD|HOST[^_])|table_prefix" | sort -d | sed "s/.*[\"']\(.*\)[\"'].*;.*/\1/" )

dbname=$(wp --skip-plugins --skip-themes eval 'echo DB_NAME;') ; 
dbuser=$(wp --skip-plugins --skip-themes eval 'echo DB_USER;') ; 
dbpass=$(wp --skip-plugins --skip-themes eval 'echo DB_PASSWORD;') ; 
dbhost=$(wp --skip-plugins --skip-themes eval 'echo DB_HOST;') ;
dbprefix=$(wp --skip-plugins --skip-themes eval 'global $wpdb;echo $wpdb->prefix;') ;

wpbackup

# EXPORT DB TABLES THAT MATCH PROD PREFIX
wp db export dev.sql --tables=$(wp db tables --all-tables-with-prefix --format=csv) 

echo -e "What directory would you like to have your staging environment created in?\n"; read devdir

# SETUP UP STAGING FOLDER
mkdir $devdir

# CLONE FILES INTO THE DEV FOLDER
cp -Rv wp* $devdir;
cp -v .htaccess $devdir 2>/dev/null || echo -e "\n\tNo .htaccess was present";
cp -v index.php $devdir 2>/dev/null || echo -e "\n\tNo index.php was present";
cp -v license.txt $devdir 2>/dev/null || echo -e "\n\tNo license.txt was present";
cp -v readme.html $devdir 2>/dev/null || echo -e "\n\tNo readme.html was present";
cp -v xmlrpc.php $devdir 2>/dev/null || echo -e "\n\tNo xmlrpc.php was present";
cp -v dev.sql $devdir  2>/dev/null || echo -e "\n\tNo Prod database was present";

cd $devdir

sleep 5 

echo -e "$COL_GREEN
Success:$COL_RESET WordPress files copied to /$devdir"

# SETUP DB
dbdevprefix="dev_"
sed -i "s/$dbprodprefix/$dbdevprefix/" dev.sql

echo -e "$COL_GREEN
Success:$COL_RESET Database prefix updated to $dbdevprefix\n"

# IMPORT DB W/ NEW PREFIX
wp db import dev.sql

rm -rf dev.sql

# UPDATE WP-CONFIG.PHP PREFIX
sed -i "s/$dbprodprefix/$dbdevprefix/" wp-config.php

sleep 5

echo -e "$COL_GREEN
Success:$COL_RESET Database prefix updated in the wp-config.php file"

# UPDATE SITE URLS TO DEV
wp --skip-plugins --skip-themes search-replace $(wp option get siteurl) $(wp option get siteurl)/$devdir --precise --recurse-objects

sleep 5

echo -e "$COL_GREEN
Success:$COL_RESET Site URLs updated to reflect /$devdir"

# NOTICE
echo -e "$COL_GREEN
Success:$COL_RESET Staging environment created in /$devdir\n"

echo -e "Long Explanation:\n- WordPress site files have been copied to /$devdir\n- A copy of the Database was made and imported using the $dbdevprefix prefix\n- The dbprefix was updated in the wp-config.php file to $dbdevprefix\n- Site URLs updated to include /$devdir\n"
}

function pushprod(){
# EXPORT DEV DB
wp db export prod.sql

DEVURL=$(wp option get siteurl)

# SYNC FILES DEV --> PROD
rsync -auvxhr --delete wp* /.. ;
rsync -auvxh --delete .htaccess /.. 2>/dev/null || echo -e "\n\tNo index.php was present/pushed.";
rsync -auvxh --delete license.txt /.. 2>/dev/null || echo -e "\n\tNo license.txt was present/pushed.";
rsync -auvxh --delete readme.html /.. 2>/dev/null || echo -e "\n\tNo readme.html was present/pushed.";
rsync -auvxh --delete xmlrpc.php /.. 2>/dev/null || echo -e "\n\tNo xmlrpc.php was present/pushed.";
rsync -auvxh --delete prod.sql /.. 2>/dev/null || echo -e "\n\tNo prod.sql was present/pushed.";

cd ..

PRODURL=$(wp option get siteurl)

dbname=$(wp --skip-plugins --skip-themes eval 'echo DB_NAME;') ; 
dbuser=$(wp --skip-plugins --skip-themes eval 'echo DB_USER;') ; 
dbpass=$(wp --skip-plugins --skip-themes eval 'echo DB_PASSWORD;') ; 
dbhost=$(wp --skip-plugins --skip-themes eval 'echo DB_HOST;') ;
dbprefix=$(wp --skip-plugins --skip-themes eval 'global $wpdb;echo $wpdb->prefix;') ;

dbdevprefix="dev_"

# UPDATE DB PREFIX
sed -i "s/$dbdevprefix/$dbprodprefix/" prod.sql

# UPDATE WP-CONFIG.PHP PREFIX
sed -i "s/$dbdevprefix/$dbprodprefix/" wp-config.php

# SET UP THE DATABASE
wp db import prod.sql

rm -rf prod.sql

echo -e "Dev URL updating from $DEVURL to $PRODURL\nIs this correct? (y/n)\n"; read input;

case $input in
	[Yy]*) wp --skip-plugins --skip-themes search-replace $DEVURL $PRODURL --precise --recurse-objects
	echo -e "$COL_GREEN
	Success:$COL_RESET Staging environment pushed to production \n"
	;;
	[Nn]*) 
	echo -e "What is the correct URL? (must match format):"; read $NEWURL
        wp --skip-plugins --skip-themes search-replace $DEVURL $NEWURL --precise --recurse-objects
	echo -e "$COL_GREEN
	Success:$COL_RESET Staging environment pushed to production \n"
	;;
	[Qq]*) 
	echo -e "Operations quit\n"
	;;
	*) invalidOption;;
esac

}

#function pushdev(){
#}

#function removedev(){
#}


function cliinstall(){
### Side Load WP-CLI ###
DIR=$(pwd)

cd

wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
chmod +x wp-cli.phar

cd $DIR

echo -e "$COL_GREEN
Choose Server Type:
$COL_RESET
(1) Shared/Cloud
(2) OHWP/VPS/DEDICATED

\tSelection: \c" ; 

read cliSelect && echo ''
case $cliSelect in
	1)	
	OLDALIAS='source `alias wp=/usr/php/54/usr/bin/php-cli /usr/local/bin/wp`'
	source `alias wp='/usr/php/54/usr/bin/php-cli -c /etc/wp-cli/php.ini ~/wp-cli.phar'`
	;; 
	2)	
	OLDALIAS='source `alias wp=/usr/local/bin/wp`'
	source `alias wp='~/wp-cli.phar'`
	;; 
	3)	return;;
	*)	invalidOption;;
esac 

trap reset_alias EXIT

echo -e "Install additional modules? y/n \c" ; 
read modSelect 
case $modSelect in
	[Yy]*) modInstall ;;
	[Nn]*) echo -e "WP-CLI Installed and Aliased\n";;
	*)	invalidOption;;
esac 
}

# reset_alias () { $OLDALIAS }

#function modInstall(){
#
#}
